# Site settings
title: "Clearwater"
description: "The Ruby rich frontend framework"
owner: "Clearwater Foundation"
profiles:
  -
    url: "http://github.com/clearwater-rb"
    name: "Github"
  -
    url: "http://github.com/clearwater-rb/clearwater"
    name: "Source"
github: "http://github.com/clearwater-rb/clearwater-rb.github.io"
logo: "http://github.com/clearwater-rb.png"
analytics: UA-18715035-9

# Build settings
markdown: redcarpet
permalink: /:title/
exclude:
  - Gemfile
  - LICENSE
  - README.md
  - CNAME
  - .ruby-gemset
  - .ruby-version
  - .gitignore
  - _mdwriter.cson
  - _sass
